dependencies:
  - python=3.11.4
  - pip=23.2.1
  - pip:
    - numpy==1.24.4
    - pandas==2.0.3
    - openpyxl==3.1.2
    - gensim==4.3.1
    - nltk==3.8.1
    - spacy==3.6.1
    - scikit-learn==1.3.0
    - seaborn==0.12.2
    - plotly==5.17.0
    - prophet==1.1.4
    - pyLDAvis==3.4.1
    - streamlit==1.26.0
    - black==23.9.1
